CREATE OR REPLACE TABLE SALES_CLEAN AS
WITH ranked AS (
    SELECT *,
    ROW_NUMBER() OVER (
        PARTITION BY ORDER_ID
        ORDER BY ORDER_DATE DESC
    ) rn
    FROM SALES_RAW
    WHERE AMOUNT IS NOT NULL
    AND STATUS != 'cancelled'
)
SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, AMOUNT, STATUS
FROM ranked
WHERE rn = 1;

CREATE OR REPLACE TABLE FACT_SALES AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    ORDER_DATE,
    AMOUNT AS REVENUE,
    STATUS
FROM SALES_CLEAN;